# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
_commit: v1.6.0
_src_path: gh:acidsailor/go-scaffolds
author: Denis Shaporov / acidsailor
author_email: d@shaporov.dev
cli_framework: cobra
go_version: '1.23'
module_path: github.com/acidsailor/ts3afkmover
project_name: ts3afkmover
project_type: cli

