version: "2"

linters:
  default: standard
  enable:
    - modernize

formatters:
  enable:
    - gofumpt
    - golines
  settings:
    gofumpt:
      extra-rules: true
    golines:
      max-len: 80
