---
version: '3.5'
x-ts3afkmover:
  &default_ts3afkmover
  build:
    context: .
  image: ghcr.io/acidsailor/ts3afkmover:latest

services:
  ts3afkmover_latest: *default_ts3afkmover
  ts3afkmover_version:
    <<: *default_ts3afkmover
    image: ghcr.io/acidsailor/ts3afkmover:0.4