name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-n-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker compose build
      - name: Actions Login
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: docker compose push